export type Env<T> = 'LESS_TERMCAP_se'|
'USER'|
'LESS_TERMCAP_ue'|
'npm_config_user_agent'|
'SSH_AGENT_PID'|
'XDG_SESSION_TYPE'|
'BUN_INSTALL'|
'npm_node_execpath'|
'SHLVL'|
'npm_config_noproxy'|
'HOME'|
'OLDPWD'|
'LESS'|
'DESKTOP_SESSION'|
'npm_package_json'|
'ZSH'|
'LSCOLORS'|
'npm_package_engines_node'|
'GTK_MODULES'|
'PAGER'|
'LESS_TERMCAP_so'|
'npm_config_userconfig'|
'npm_config_local_prefix'|
'SYSTEMD_EXEC_PID'|
'DBUS_SESSION_BUS_ADDRESS'|
'P9K_TTY'|
'COLORTERM'|
'COLOR'|
'IM_CONFIG_PHASE'|
'GTK_IM_MODULE'|
'LOGNAME'|
'LESS_TERMCAP_us'|
'_P9K_SSH_TTY'|
'_'|
'npm_config_prefix'|
'npm_config_npm_version'|
'XDG_SESSION_CLASS'|
'npm_config_registry'|
'USERNAME'|
'TERM'|
'npm_config_cache'|
'GNOME_DESKTOP_SESSION_ID'|
'WINDOWPATH'|
'npm_config_node_gyp'|
'PATH'|
'SESSION_MANAGER'|
'GDM_LANG'|
'NODE'|
'npm_package_name'|
'GNOME_TERMINAL_SCREEN'|
'XDG_MENU_PREFIX'|
'XDG_RUNTIME_DIR'|
'DISPLAY'|
'XDG_CURRENT_DESKTOP'|
'LANG'|
'XDG_SESSION_DESKTOP'|
'GNOME_TERMINAL_SERVICE'|
'XMODIFIERS'|
'XAUTHORITY'|
'LS_COLORS'|
'npm_lifecycle_script'|
'SSH_AUTH_SOCK'|
'GOPATH'|
'SHELL'|
'npm_package_version'|
'npm_lifecycle_event'|
'QT_ACCESSIBILITY'|
'GDMSESSION'|
'LESS_TERMCAP_mb'|
'GPG_AGENT_INFO'|
'P9K_SSH'|
'QT_IM_MODULE'|
'LESS_TERMCAP_md'|
'npm_config_globalconfig'|
'npm_config_init_module'|
'PWD'|
'LESS_TERMCAP_me'|
'npm_execpath'|
'XDG_DATA_DIRS'|
'_P9K_TTY'|
'npm_config_global_prefix'|
'npm_command'|
'VTE_VERSION'|
'INIT_CWD'|
'EDITOR'|
'APP_NAME'|
'APP_ENV'|
'APP_KEY'|
'APP_DEBUG'|
'APP_TIMEZONE'|
'APP_URL'|
'APP_LOCALE'|
'DB_CONNECTION'|
'DB_HOST'|
'DB_PORT'|
'DB_DATABASE'|
'DB_USERNAME'|
'DB_PASSWORD'|
'MAIL_MAILER'|
'MAIL_HOST'|
'MAIL_PORT'|
'MAIL_USERNAME'|
'MAIL_PASSWORD'|
'MAIL_ENCRYPTION'|
'MAIL_FROM_ADDRESS'|
'MAIL_FROM_NAME' | T;